[theme]
base = "light"
primaryColor = "#D9534F"
backgroundColor = "#F9F6F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1D20"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"
enableXsrfProtection = true
